# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gergely Horváth
email: horvath@gergely.xyz
description: >-
  The personal site of Gergely Horváth
baseurl: ""
url: "https://gergely.xyz"
github_username:  gergely-xyz
date_format: "%Y-%m-%d"
time_format: "%H:%M"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      type: posts
    values:
      layout: "post"
      permalink: "/:categories/:title/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/